//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kursach
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class rezervEntities1 : DbContext
    {
        public rezervEntities1()
            : base("name=rezervEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cabinet> cabinet { get; set; }
        public virtual DbSet<fio> fio { get; set; }
        public virtual DbSet<spec> spec { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
